spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carforyou
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      show-sql: false
      properties:
        hibernate:
          jdbc:
            time_zone: UTC

  mail:
    host: smtp.gmail.com
    port: 587
    username: "kevinaldroniya190297@gmail.com"
    password: "dgpj tyrb fhli hwkn"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true